(() => {
  const overlay=document.querySelector("#wildcardOverlay"), list=document.querySelector("#wildcardList");
  if(!overlay||!list) return;
  overlay.querySelector("header span")?.remove();
  document.querySelector("#wildcardTitle").textContent="와일드카드";
  const toggle=document.querySelector("#wildcardToggle"), status=document.querySelector("#wildcardStatus");
  const entries=document.querySelector("#wildcardEntries"), token=document.querySelector("#wildcardToken");
  const insert=document.querySelector("#wildcardInsert"), search=document.querySelector("#wildcardSearch");
  insert?.remove();
  search.placeholder="선택한 와일드카드에서 후보 검색";
  const interactionHint=document.createElement("small");interactionHint.className="wildcard-interaction-hint";interactionHint.textContent=window.matchMedia("(pointer: coarse)").matches?"목록을 터치해 선택하고, 꾹 눌러 일반 프롬프트에 추가하거나 제거합니다.":"목록을 더블 클릭하면 일반 프롬프트의 맨 뒤에 추가하거나 제거합니다.";search.insertAdjacentElement("afterend",interactionHint);
  let inventory=[], source="BUILT_IN", selected=null, exclusions={};
  const builtinLabels={background:"배경",composition:"구도",expression:"표정",hair_style_female:"여성 헤어스타일",outfit:"의상",pose:"포즈",prop:"소품"};
  function displayName(item){const english=item.name.replaceAll("_"," "),korean=item.source==="BUILT_IN"?builtinLabels[item.name]:null;return korean?`${korean} | ${english}`:(item.display_name||english);}
  const allowedPromptIds=new Set(["fixedPromptInput","generalPromptInput","qualityPromptInput","artistPromptInput","triggerPromptInput","negativeFixedPromptInput","negativeQualityPromptInput","negativeArtistPromptInput","negativePrompt","inpaintPromptInput","inpaintNegativePromptInput"]);
  function setEnabled(){window.lakisWildcardEnabled=true;window.dispatchEvent(new CustomEvent("lakis:wildcard-enabled",{detail:true}));}
  function toggleWildcard(item,button){select(item,button);promptWildcardNames().includes(item.name)?removeActiveWildcard(item.name):insertSelectedWildcard();}
  function addLongPress(button,item){let timer=null,startX=0,startY=0,suppressClick=false;const cancel=()=>{if(timer!==null)clearTimeout(timer);timer=null;};button.addEventListener("pointerdown",event=>{if(event.pointerType==="mouse")return;startX=event.clientX;startY=event.clientY;suppressClick=false;cancel();timer=setTimeout(()=>{timer=null;suppressClick=true;toggleWildcard(item,button);navigator.vibrate?.(20);},600);});button.addEventListener("pointermove",event=>{if(timer!==null&&(Math.abs(event.clientX-startX)>10||Math.abs(event.clientY-startY)>10))cancel();});button.addEventListener("pointerup",cancel);button.addEventListener("pointercancel",cancel);button.addEventListener("contextmenu",event=>{if(event.pointerType!=="mouse")event.preventDefault();});button.addEventListener("click",event=>{if(suppressClick){event.preventDefault();event.stopImmediatePropagation();suppressClick=false;}} ,true);}
  function render(){list.replaceChildren();const visible=inventory.filter(item=>item.source===source),used=new Set(promptWildcardNames());if(!visible.length){list.textContent=source==="USER"?"내 와일드카드가 없습니다. 폴더에 .txt 파일을 추가해 주세요.":"표시할 와일드카드가 없습니다.";return;}for(const item of visible){const button=document.createElement("button");button.type="button";button.dataset.wildcardName=item.name;button.classList.toggle("is-used",used.has(item.name));button.innerHTML=`<span>${displayName(item)}</span><small>${item.entry_count}</small>`;button.onclick=()=>select(item,button);button.ondblclick=()=>toggleWildcard(item,button);addLongPress(button,item);list.append(button);}}
  function excludedFor(item){return new Set(Array.isArray(exclusions[item.name])?exclusions[item.name]:[]);}
  function saveExclusions(){window.dispatchEvent(new CustomEvent("lakis:wildcard-exclusions",{detail:structuredClone(exclusions)}));}
  function renderEntries(){entries.replaceChildren();if(!selected)return;const excluded=excludedFor(selected),query=search.value.trim().toLowerCase();document.querySelector("#wildcardUseCount").textContent=`사용 ${selected.entries.length-excluded.size} / ${selected.entries.length}`;const visible=selected.entries.filter(value=>!query||value.toLowerCase().includes(query));if(!visible.length){const empty=document.createElement("small");empty.textContent="검색 결과가 없습니다.";entries.append(empty);return;}visible.forEach(value=>{const label=document.createElement("label");label.className="wildcard-entry-option";const box=document.createElement("input");box.type="checkbox";box.checked=!excluded.has(value);box.onchange=()=>{const next=excludedFor(selected);box.checked?next.delete(value):next.add(value);exclusions[selected.name]=[...next];saveExclusions();renderEntries();renderActive();};label.append(box,document.createTextNode(value));entries.append(label);});}
  function promptWildcardNames(){const found=[];allowedPromptIds.forEach(id=>{const field=document.getElementById(id);for(const match of String(field?.value||"").matchAll(/__([A-Za-z0-9_][A-Za-z0-9_\-/]{0,199})__/g))if(!found.includes(match[1]))found.push(match[1]);});return found;}
  function syncUsedListStyles(){const used=new Set(promptWildcardNames());list.querySelectorAll("button[data-wildcard-name]").forEach(button=>button.classList.toggle("is-used",used.has(button.dataset.wildcardName)));}
  function removeActiveWildcard(name){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),pattern=new RegExp(`__${escaped}__`,"g");allowedPromptIds.forEach(id=>{const field=document.getElementById(id);if(!field||!pattern.test(field.value))return;pattern.lastIndex=0;field.value=field.value.replace(pattern,"").replace(/\s*,\s*,+/g,", ").replace(/^\s*,\s*/,"").replace(/\s*,\s*$/,"").trim();field.dispatchEvent(new Event("input",{bubbles:true}));});renderActive();}
  function renderActive(){const host=document.querySelector("#activeWildcards");host.replaceChildren();const names=promptWildcardNames(),panelTokens=document.querySelector("#wildcardPanelActiveTokens");panelTokens.textContent=names.length?names.map(name=>`__${name}__`).join(", "):"사용 중인 와일드카드 없음";syncUsedListStyles();if(!names.length){const empty=document.createElement("small");empty.textContent="프롬프트에 삽입된 와일드카드가 없습니다.";host.append(empty);return;}names.forEach(name=>{const item=[...inventory].reverse().find(entry=>entry.name===name);const card=document.createElement("div");card.className="active-wildcard-item";const used=item?item.entries.length-excludedFor(item).size:0;card.innerHTML=`<strong>${item?displayName(item):name}</strong><code>__${name}__</code><small>${item?`사용 ${used} / ${item.entries.length}`:"파일을 찾을 수 없음"}</small>`;host.append(card);});}
  function select(item,button){selected=item;list.querySelectorAll("button").forEach(node=>node.classList.toggle("active",node===button));document.querySelector("#wildcardSelectionName").textContent=displayName(item);document.querySelector("#wildcardSelectionMeta").textContent=`${item.source} · ${item.relative_path} · ${item.entry_count}개`;renderEntries();token.textContent=`__${item.name}__`;}
  async function refresh(){status.textContent="불러오는 중…";const response=await fetch("/api/wildcards",{cache:"no-store"});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"와일드카드를 불러오지 못했어요.");inventory=payload.items||[];window.lakisUserWildcardRoot=payload.user_root||"";selected=null;entries.replaceChildren();render();renderActive();status.textContent=`${inventory.length}개 파일`;}
  document.querySelector("#wildcardOpen").onclick=()=>{overlay.hidden=false;refresh().catch(error=>status.textContent=error.message);};document.querySelector("#wildcardClose").onclick=()=>overlay.hidden=true;overlay.addEventListener("click",event=>{if(event.target===overlay)overlay.hidden=true;});document.querySelectorAll("[data-wildcard-source]").forEach(button=>button.onclick=()=>{source=button.dataset.wildcardSource;selected=null;search.value="";document.querySelectorAll("[data-wildcard-source]").forEach(node=>node.classList.toggle("active",node===button));render();renderEntries();});search.oninput=renderEntries;document.querySelector("#wildcardRefresh").onclick=()=>refresh().catch(error=>status.textContent=error.message);document.querySelector("#wildcardFolder").onclick=()=>fetch("/api/open-wildcard-folder",{method:"POST"}).catch(()=>{});
  document.querySelector("#wildcardIncludeAll").onclick=()=>{if(!selected)return;delete exclusions[selected.name];saveExclusions();renderEntries();renderActive();};document.querySelector("#wildcardReset").onclick=()=>{if(!selected)return;delete exclusions[selected.name];saveExclusions();renderEntries();renderActive();};
  document.addEventListener("input",event=>{if(event.target instanceof HTMLTextAreaElement&&allowedPromptIds.has(event.target.id))renderActive();});
  function insertSelectedWildcard(){if(!selected)return;const promptField=document.querySelector("#generalPromptInput"),end=promptField.value.length,before=promptField.value,tokenValue=`__${selected.name}__`,prefix=before.trim()&&!/[,\n]\s*$/.test(before)?", ":"";promptField.setRangeText(`${prefix}${tokenValue}, `,end,end,"end");promptField.dispatchEvent(new Event("input",{bubbles:true}));status.textContent="";renderActive();}
  window.lakisApplyWildcardState=()=>setEnabled();
  window.lakisApplyWildcardExclusions=value=>{exclusions=value&&typeof value==="object"?structuredClone(value):{};renderEntries();renderActive();};
  window.lakisResolveWildcardsForGeneration=async({prompt,inpaint,seed})=>{const response=await fetch("/api/resolve-wildcards",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,inpaint,seed,enabled:Boolean(window.lakisWildcardEnabled),excluded:exclusions})});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"와일드카드를 적용하지 못했어요.");return payload;};
  setEnabled();
})();
